### ISSUE TITLE
Create issue and pull request templates

### ISSUE THREAD

**Issue by nsylke** [trpkit/typicalbot.com#17]
Create issue and pull request templates using the new config format which allows it to be a form instead of markdown.

**Comment by tjrgg** [comment]
I'm actually thinking against using a form for issues.

**Comment by nsylke** [comment]
If you want to tackle the issue and not use forms, I am okay with that. I personally found forms to be a bit more intuitive and helpful.

**Comment by tjrgg** [comment]
I'm only interested in automating tasks related to issues (closing, updating status, etc). I'm not seeing the benefit of a standardized form of issues or pull requests. All that's really necessary is a sentence or two about the issue or a sentence or two about what a pull request does.
